# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

[tools]
lune = "lune-org/lune@0.10.4"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.6.1"
darklua = "seaofvoices/darklua@0.17.3"
selene = "Kampfkarren/selene@0.30.0"
stylua = "JohnnyMorganz/StyLua@2.3.1"
